config/routes.rb
SeatYourself::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :categories
  
  resources :restaurants do
    resources :reservations, only: :create
    resources :reviews, :except => [:index]
  end

  resources :users
  resources :sessions
  root :to => "restaurants#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seat_Yourself Beta</title>
  <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

  <body>
    <header class="navbar navbar-inverse">
        <div class="container">
          <%= link_to "Seat_Yourself", "/restaurants/", id: "logo" %>
          <nav>
            <ul class="nav nav-pills pull-right">
              <li><%= link_to "Home", "/restaurants/" %></li>
              <li><%= link_to "New Restaurant", "/restaurants/new" %></li>
              <li><%= link_to "New Category", "/categories/new" %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
               
    <div class="container">
      <%= yield %>
    </div>
<p>
    <div id="usercontainer">
                  <% if current_user %>
                    Logged in as <%= current_user.username %>
                    | <%= link_to "Log out", logout_path %>
                    | <%= link_to "View Your Reservations", user_path(current_user.id) %>
                    <% else %>
                    <%= link_to "Register", signup_path %> or
                    <%= link_to "Log in", login_path %>.
                  <% end %>
                    
                </div>

  </body>
</html>